version: '3.8'
services:
  django:
    image: django-celery
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/ # ensure  the WORKDIR in Dockerfile is /usr/src/app
    ports:
      - "8000:8000" # browser:container
    environment:
      - DEBUG=True
      - SECRET_KEY=8940129401294gasgas85212dsa
      - ALLOWED_HOSTS=localhost, 127.0.0.1